### ISSUE TITLE
Three Files with the Extension .ino prevent compile in Windows.

### ISSUE THREAD

**Issue by mitag** [sparkfun/OpenLCD#15] opened 2019-01-04 03:56 UTC
The firmware consists of several files, three of which have the extension .ino. Yesterday I bought a 20x4 SerLCD and this has the known backlight bug in the firmware. On your side the procedure is described very well, but I could not compile the firmware under Windows 10, because only one file may have the extension .ino. Trying to rename the files to header files caused several problems. So I installed everything under Debian Linux and the three files with the extension .ino don't interfere! I forked the firmware and uploaded the binary file in the fork, because you fixed the bug but didn't upload a binary file. It's not that bad, but just to fix the bug, the steps are too extensive for most users.

[https://www.youtube.com/watch?v=OjE9r5SRFKM](url)

**Comment by mitag** [comment] 2019-01-04 13:54
For now, I've written a small [workeround](https://github.com/mitag/OpenLCD/blob/master/firmware/OpenLCD/README.md) in my fork.

**Comment by nseidle** [comment] 2019-01-04 18:04
Hmm. Weird. It is correct to have multiple INO files in a given directory. It's called tabs; we do it a lot to segment large sketches into various relevant buckets. Arduino opens multiple INOs correctly as shown

![image](https://user-images.githubusercontent.com/117102/50703004-eb50b680-100f-11e9-9afa-25e69ba89789.png)

Sorry for not pushing a hex file. I can get that into the next release.

Thanks for trying to upgrade your 20x4! Let me know if you continue to have issues. I'm going to close this issue because I don't *think* it's an issue. Please correct me if you still have problems.

**Closed by nseidle** 2019-01-04 18:04 UTC

**Comment by per1234** [comment] 2019-01-06 01:56
The issue turned out to be caused by a bug in arduino-builder, which has already been fixed.

Details: https://github.com/arduino/Arduino/issues/8360#issuecomment-451708341
